### ISSUE TITLE
Dependency conflicts with Firebase Admin SDK

### ISSUE THREAD

**Issue by baldapps** [actions-on-google/actions-on-google-java#27]
There's a conflict between actions-on-google 1.3.0 and Firebase Admin SDK 6.9.0. When you try to use both packages in a pom.xml you receive errors for conflicts about several packages. It would be great to update dependencies of actions-on-google package.

```
Could not resolve version conflict among [com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-protobuf-lite:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-stub:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-auth:jar:1.15.1 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.api:gax-grpc:jar:1.46.1 -> io.grpc:grpc-alts:jar:1.21.0 -> io.grpc:grpc-grpclb:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.api:gax-grpc:jar:1.46.1 -> io.grpc:grpc-alts:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.grpc:grpc-netty-shaded:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.opencensus:opencensus-contrib-grpc-util:jar:0.21.0 -> io.grpc:grpc-core:jar:1.19.0]

org.eclipse.aether.collection.UnsolvableVersionConflictException: Could not resolve version conflict among [com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-protobuf-lite:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-stub:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, com.google.actions:actions-on-google:jar:1.3.0 -> io.grpc:grpc-auth:jar:1.15.1 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.api:gax-grpc:jar:1.46.1 -> io.grpc:grpc-alts:jar:1.21.0 -> io.grpc:grpc-grpclb:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.api:gax-grpc:jar:1.46.1 -> io.grpc:grpc-alts:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.grpc:grpc-netty-shaded:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], com.google.firebase:firebase-admin:jar:6.9.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.opencensus:opencensus-contrib-grpc-util:jar:0.21.0 -> io.grpc:grpc-core:jar:1.19.0]
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.newFailure(NearestVersionSelector.java:150)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.backtrack(NearestVersionSelector.java:111)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.selectVersion(NearestVersionSelector.java:84)
	at org.eclipse.aether.util.graph.transformer.ConflictResolver.transformGraph(ConflictResolver.java:187)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:273)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:215)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
	at org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:530)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:492)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:496)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:298)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by taycaldwell** [comment]
Hi @baldapps,

Are you still running into this issue?

Best,

**Comment by sarasini** [comment]
I have the same problem

**Comment by baldapps** [comment]
> Hi @baldapps,
> 
> Are you still running into this issue?
> 
> Best,

yes
