### ISSUE TITLE
SmartHomeApp.reportState error

### ISSUE THREAD

**Issue by kingskylar** [actions-on-google/actions-on-google-java#30]
Is this error below because the grpc-core version is too low?
```
io.grpc.internal.ManagedChannelOrphanWrapper line:163 -*~*~*~ Channel ManagedChannelImpl{logId=144961, target=homegraph.googleapis.com} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410) [grpc-core-1.15.1.jar:1.15.1]
	at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:126) [actions-on-google-1.5.0.jar:?] 
```

**Comment by cbeaujoin** [comment]
No, this means that the channel to Dialogflow API is not closed programmatically.
To safely close the channel as it is said :
 "Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true."

**Comment by kingskylar** [comment]
Thank you for reply!
I use the method in actions-on-google-1.5.0.jar to report states to google.Is there a problem with this method?
```
/**
     * Sends a ReportState command to the Home Graph, which will store a device's current state.
     * This should be called after a device receives an EXECUTE request, or if the device has
     * changed state through a means outside of your smart home Action.
     *
     * @param request A payload containing a series of devices and their connected states
     * @return A response to the API call
     */
    fun reportState(request: HomeGraphApiServiceProto.ReportStateAndNotificationRequest):
            HomeGraphApiServiceProto.ReportStateAndNotificationResponse {
        if (this.credentials == null) {
            throw IllegalArgumentException("You must pass credentials in the app constructor")
        }
        val channel = ManagedChannelBuilder.forTarget("homegraph.googleapis.com").build()

        val blockingStub = HomeGraphApiServiceGrpc.newBlockingStub(channel)
                // See https://grpc.io/docs/guides/auth.html#authenticate-with-google-3.
                .withCallCredentials(MoreCallCredentials.from(this.credentials))

        return blockingStub.reportStateAndNotification(request)

    }
```

**Comment by cbeaujoin** [comment]
You could try something like this :

```
/**
     * Sends a ReportState command to the Home Graph, which will store a device's current state.
     * This should be called after a device receives an EXECUTE request, or if the device has
     * changed state through a means outside of your smart home Action.
     *
     * @param request A payload containing a series of devices and their connected states
     * @return A response to the API call
     */
    fun reportState(request: HomeGraphApiServiceProto.ReportStateAndNotificationRequest):
            HomeGraphApiServiceProto.ReportStateAndNotificationResponse {
        if (this.credentials == null) {
            throw IllegalArgumentException("You must pass credentials in the app constructor")
        }
        val channel = ManagedChannelBuilder.forTarget("homegraph.googleapis.com").build()

        val blockingStub = HomeGraphApiServiceGrpc.newBlockingStub(channel)
                // See https://grpc.io/docs/guides/auth.html#authenticate-with-google-3.
                .withCallCredentials(MoreCallCredentials.from(this.credentials))

        ListenableFuture<HomeGraphApiServiceProto.ReportStateAndNotificationResponse> response = blockingStub.reportStateAndNotification(request);
        channel.shutdown();
        try {
            channel.awaitTermination(500, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
        return response;
    }
```

**Comment by Fleker** [comment]
I've not seen that error before. Has it only begun happening recently? How are you hosting the code?

**Comment by kingskylar** [comment]
This error has been around, causing my application to die because of increased memory.I just used the method `SmartHomeApp.reportState` in actions-on-google-1.5.0.jar,May be caused by a network connection problem If the network is too slow or not connected.

**Comment by Fleker** [comment]
How are you hosting the code? Google App Engine? Some other provider like AWS?

**Comment by kingskylar** [comment]
AWS

**Comment by Fleker** [comment]
Can you try the suggestion that @cbeaujoin created? Maybe the channel needs to be shutdown after use, or instantiated once in the run environment instead of being continually created?

I've not seen any memory issues, so this may be useful for performance improvements.

**Comment by RayBa82** [comment]
I have the same error when using report state. How should i try the suggestions? Changing the code and building the project?

**Comment by Fleker** [comment]
Does shutting down the channel work after it is used?

**Comment by RayBa82** [comment]
I dont know what you are talking about? I am using just SmartHomeApp.reportState.
There is no method to shut down a "channel"

**Comment by RayBa82** [comment]
BTW I have a working implementation for node, i just converted this app to java because node sucks ;-) And now I get this error. So the error has to be in the java implementation.

After having done all the work i am very frustrated to see that the java implementation has so much errors. This all feels like an early alpha version. I expect better from a company like google.

Switching to Alexa becomes more and more attractive, not only because of the much wider supported device range, the development happens so much faster over there.

**Comment by Fleker** [comment]
@RayBa82 if you look at the source code for the library, you will see the underlying gRPC implementation.

Are you also using AWS for hosting your project?

**Comment by Fleker** [comment]
Can you try copying the suggested function @cbeaujoin has and calling that instead of the current function?

**Comment by RayBa82** [comment]
Ok now i got it, I will try that tonight CET ;-)

**Comment by Fleker** [comment]
Thanks. Let me know. I have not experienced any issues running on Google App Engine, so it'll be interesting to see if the behavior exists in other instances.

**Comment by RayBa82** [comment]
This really seems to fix the problem. I could not reproduce the error with the fix.
Thanks.

**Comment by RayBa82** [comment]
This code works without any problem:
`/**
     * Sends a ReportState command to the Home Graph, which will store a device's current state.
     * This should be called after a device receives an EXECUTE request, or if the device has
     * changed state through a means outside of your smart home Action.
     *
     * @param request A payload containing a series of devices and their connected states
     * @return A response to the API call
     */
    fun report(request: HomeGraphApiServiceProto.ReportStateAndNotificationRequest):
            HomeGraphApiServiceProto.ReportStateAndNotificationResponse {
        requireNotNull(this.credentials) { "You must pass credentials in the app constructor" }
        val channel = ManagedChannelBuilder.forTarget("homegraph.googleapis.com").build()

        val blockingStub = HomeGraphApiServiceGrpc.newBlockingStub(channel)
                // See https://grpc.io/docs/guides/auth.html#authenticate-with-google-3.
                .withCallCredentials(MoreCallCredentials.from(this.credentials))
        val response = blockingStub.reportStateAndNotification(request)
        channel.shutdown()
        return response
    }`

waiting for termination seems not to be necessary

**Comment by RayBa82** [comment]
Just for further Info:

This error never happened with a single request. But if my applications was sending multiple report state requests per second (about 6) this error has always been reproducable.

Maybe you can reproduce this with a load test in App Engine too.

**Comment by cbeaujoin** [comment]
Hi,

I had the same problem using the google-cloud-dialogflow lib and I don't exactly remind the cause.
But it seems Google App Engine internally manage grpc channels.
When deploying to an other environment, the ExecutorService has to be manage manually as explain here : [google-cloud-java/issues/4211](https://github.com/googleapis/google-cloud-java/issues/4211#issuecomment-449591202)

**Comment by Fleker** [comment]
@proppy can you assist with this issue?

**Comment by kingskylar** [comment]
@Fleker How is this issue? Because of this issue, I have to turn off the report function.For authentication i have to use this function now.Please fix it soon,thank you!

**Comment by RayBa82** [comment]
None of the solutions with manually closing the channel worked for me in the long run. After some time the error always occured again.

What actually worked for me is making 
`val channel: ManagedChannel = ManagedChannelBuilder.forTarget("homegraph.googleapis.com").build()` 
a class field with direct initialization.

But i have to say im running a spring boot application and my SmartHomeApp class is a spring bean. So i only have one instance of the class for my whole application.

But this is running stable without any error over weeks.

**Comment by Fleker** [comment]
Where are you hosting it?

**Comment by RayBa82** [comment]
It runs on a virtual private server as docker container.

**Comment by kingskylar** [comment]
As long as i enable the report function,lots of the error happend,below is a log screenshot.
<img width="801" alt="error" src="https://user-images.githubusercontent.com/38035225/72229575-aed47500-35ea-11ea-94b3-5f2de2ea944c.png">

**Comment by HuangDayu** [comment]
Hello, I am using version 1.8 and also encountering this problem, how can I solve it? Thank you.

```shell
2020-05-19 10:28:48.521 ERROR 19974 --- [http-nio-8016-exec-17] i.g.i.ManagedChannelOrphanWrapper        : *~*~*~ Channel ManagedChannelImpl{logId=4349, target=homegraph.googleapis.com} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.

java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103) ~[grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53) ~[grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44) ~[grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410) ~[grpc-core-1.15.1.jar:1.15.1]
        at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:126) ~[actions-on-google-1.8.0.jar:na]
        ....
```

**Comment by murilobaliego** [comment]
What is the solution for this error as issue is closed? I'm getting the same error : 
2020-06-12 13:31:50.798 BRT
io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue: *~*~*~ Channel ManagedChannelImpl{logId=70, target=homegraph.googleapis.com} was not shutdown properly!!! ~*~*~* (ManagedChannelOrphanWrapper.java:151)
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.

**Comment by Fleker** [comment]
@proppy can you provide some additional guidance on this issue?

**Comment by proppy** [comment]
It seems that `action-on-google-java` creates a new `ManagedChannel` on every request:
https://github.com/actions-on-google/actions-on-google-java/blob/master/src/main/kotlin/com/google/actions/api/smarthome/SmartHomeApp.kt#L126

As pointed by @cbeaujoin in https://github.com/actions-on-google/actions-on-google-java/issues/30#issuecomment-529400776 and comments in the official gRPC sample for Java:
https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java#L96
such channels should be explicitly shutdown when no longer being used to prevent leaks.

A workaround could be for client to directly depends on the `HomeGraph API Client Library for Java
` https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-homegraph/v1 instead of using the `reportState` helper and reuse a single channel tied to the lifetime of the application.

**Comment by kingskylar** [comment]
@Fleker Hi,how is this issue?it's a long time.

**Comment by fangquan456** [comment]
@proppy proppy can you supply a demo?(A workaround could be for client to directly depends on the HomeGraph API Client Library for Java )

**Comment by wuhaoisme** [comment]
actionsApp.reportState(request);

change as 

 HomeGraphApiServiceGrpc.HomeGraphApiServiceBlockingStub stub =
              HomeGraphApiServiceGrpc.newBlockingStub(channel)
                      .withCallCredentials(MoreCallCredentials.from(actionsApp.getCredentials()));
 stub.reportStateAndNotification(request);

finally
releaseChannel(channel)
