### ISSUE TITLE
report state need a Integer value type

### ISSUE THREAD

**Issue by kingskylar** [actions-on-google/actions-on-google-java#46]
The spectrumRgb report state need a integer value,but the Value build only has a number type and will turn to Double type.
https://developers.google.com/assistant/smarthome/traits/colorsetting#device-states

below is the main error log info:

`
  value {
          struct_value {
            fields {
              key: "color"
              value {
                struct_value {
                  fields {
                    key: "spectrumRgb"
                    value {
                      number_value: 9109504.0
                    }
                  }
                }
              }
            }
          }
        }

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233) ~[grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214) ~[grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139) ~[grpc-stub-1.15.1.jar:1.15.1]
        at com.google.home.graph.v1.HomeGraphApiServiceGrpc$HomeGraphApiServiceBlockingStub.reportStateAndNotification(HomeGraphApiServiceGrpc.java:425) ~[actions-on-google-1.8.0.jar:?]
        at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:132) ~[actions-on-google-1.8.0.jar:?]`

**Comment by Fleker** [comment]
Can you update the key you're sending to be "spectrumRGB" as capitalized?

**Comment by kingskylar** [comment]
The guide noted reporting state use "spectrumRgb",i will test use "spectrumRGB".
![0E4FD599-BB06-4173-B4DF-7B182DFC998F](https://user-images.githubusercontent.com/38035225/75962361-999b0900-5efe-11ea-9a2b-1c4fba0b43db.png)

**Comment by Fleker** [comment]
There is also a note a bit higher on the page.

![image](https://user-images.githubusercontent.com/3291635/76000416-ad7c4600-5ed1-11ea-901e-19aff914a400.png)

**Comment by kingskylar** [comment]
yes,you are right,thank you.
